### ISSUE TITLE
Hotel Teaser With Image

### ISSUE THREAD

**Issue by solaris007** [hlxsites/choice#17]
implement "image near hotels" block.
- Prominent image with link/text in lower right corner
- Side column with description and location icon

Content so far: 
![Screenshot 2023-02-09 at 08 23 09](https://user-images.githubusercontent.com/1872195/217744841-a3b0e0d6-5f8f-4a3b-b6f7-567d2fd663a4.png)

How it looks on https://www.choicehotels.com/explore/road-trips/best-winter-road-trips

Mobile:
![Screenshot 2023-02-09 at 08 23 36](https://user-images.githubusercontent.com/1872195/217744939-c79eacec-78da-4600-949c-7977e439e330.png)

Desktop:
![Screenshot 2023-02-09 at 08 23 48](https://user-images.githubusercontent.com/1872195/217744971-6e2840b2-bf08-4005-8ece-6096cb43c511.png)

**Comment by cuzuco2** [comment]
Reopen to fix the block to use only css

**Comment by cuzuco2** [comment]
working on css only solution

**Comment by solaris007** [comment]
Also see a difference in the link on the image (original is left):
- background black with opacity
- reaches outside of image on the right

![Screenshot 2023-02-14 at 15 08 28](https://user-images.githubusercontent.com/1872195/218762111-1f5e4d4d-82f6-402e-ac70-e5bc308a6ba8.png)
